# Generated by Django 4.2.5 on 2024-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpverifiaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerregistration',
            old_name='company_pan_card',
            new_name='comany_pan_card',
        ),
        migrations.RenameField(
            model_name='employerregistration',
            old_name='phone_number',
            new_name='phonpe_number',
        ),
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-09-16', max_length=10),
        ),
    ]
