# Generated by Django 4.2.5 on 2024-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_company_pan_card_employerregistration_comany_pan_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpMyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('education', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('O', 'Other')], max_length=1, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('expected_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('currenet_location', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_set', models.TextField()),
                ('previours_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
