# Generated by Django 4.2.5 on 2024-09-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_empmyprofile_alter_customuser_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmyprofile',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
