# Generated by Django 4.2.5 on 2024-09-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_empmyprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('passowrd', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-09-17', max_length=10),
        ),
    ]
