# Generated by Django 4.2.5 on 2024-09-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailusername_alter_otpverifiaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailusername',
            old_name='passowrd',
            new_name='passowrds',
        ),
        migrations.RenameField(
            model_name='emailusername',
            old_name='username',
            new_name='usernames',
        ),
    ]
