# Generated by Django 4.2.5 on 2024-09-17 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_passowrd_emailusername_passowrds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailusername',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
