# Generated by Django 4.2.5 on 2024-09-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_emailusername_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailusername',
            old_name='passowrds',
            new_name='passowrd',
        ),
        migrations.RenameField(
            model_name='emailusername',
            old_name='usernames',
            new_name='username',
        ),
    ]
