# Generated by Django 4.2.5 on 2024-09-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_passowrds_emailusername_passowrd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-09-19', max_length=10),
        ),
    ]
