# Generated by Django 4.2.5 on 2024-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_advancedjobsearch_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
