# Generated by Django 4.2.5 on 2024-09-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_employerregistration_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-09-25', max_length=10),
        ),
    ]
