# Generated by Django 4.2.5 on 2024-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_otpverifiaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedjobsearch',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancedjobsearch',
            name='companyType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-09-26', max_length=10),
        ),
    ]
