# Generated by Django 4.2.5 on 2024-08-28 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedashboard',
            name='upload_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploadsimg/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeedashboard',
            name='upload_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
