# Generated by Django 4.2.5 on 2024-08-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0002_employeedashboard_upload_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('select_time', models.TimeField(auto_now=True, null=True)),
                ('problem_type', models.CharField(blank=True, choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('support', 'Support'), ('other', 'Other')], max_length=200, null=True)),
                ('explain_the_problem', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
