# Generated by Django 4.2.5 on 2024-09-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0004_contactpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
