# Generated by Django 4.2.5 on 2024-03-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paymentapi", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
